watchexec/watchexec

- src/main.rs
> Option to run command initially, before first file change 

- README.md
Just added spaces so the markdown recognises the headers.
> Fix headers in Readme file.

- src/process.rs
`process_exec` is stable since `1.15.0`
```rust
#[stable(feature = "process_exec", since = "1.15.0")]
```
> Use before_exec as process_exec landed in stable

- doc/watchexec.1
- doc/watchexec.1.html
- doc/watchexec.1.ronn
- src/cli.rs
This worked locally, seems simple enough but I've also never written Rust before, so open to any recommendations on more idiomatic ways to do this.
Also, not sure if the docs are autogenerated from somewhere, in which case I'm happy to gen them up, or if I should manually add them
> add no-default-ignore option, fixes #45

- src/cli.rs
This fixes screen clearing for me on Windows. 
Thanks for `watchexec`, I use it all day long!
> fix screen clearing on windows

- src/main.rs
- src/run.rs
issue #71
- Add some basic error handling
- Convert missing folder panic to error
Side note: I'm not sure what error code should be used for windows.
> don't panic on missing folder

- src/cli.rs
- src/process.rs
- src/run.rs
Fixes #82
Fixes #87 
[minor-bump; changes library interface]
> Wrap whitespace and quotes in command arguments

- .gitignore
- Cargo.toml
- src/cli.rs
- src/lib.rs
- src/main.rs
- src/pathop.rs
- src/run.rs
Major changes for c bindings integration as third party crate (see project: github/InfinityMod/watchexec_c). Changed version to 1.9.3 for third party crate compatibility detection.
> C-binding support as third party crate.

- README.md
- ci/before_deploy.sh
- completions/zsh
> Add zsh completions for #118 (credit @Mange)

- src/run.rs
Howdy! I just filed /#133 where I described a problem encountered while working on `cargo-watch`. This PR addresses the problem described in that PR; I hope it's not too presumptuous of me to make this kind of breaking change out of the blue like this, but I thought it would be better to ask forgiveness than squander a rare fit of motivation to contribute to an open source project ;).
A quick summary of the changes made here:
* ~Remove the `H` type parameter to `watchexec::watch`~
* Remove the `watchexec::Args` argument from `watchexec::watch`
* Add a `& H` argument to `watchexec::watch` with the same `where H: Handler` constraint.
* Remove `new` from the `Handler` trait.
* Move the `new` implementation into the `impl Handler` block.
* Add `fn args(&self) -> &Args; ` to `Handler` to …
> #133: leave Handler initialization to watch caller

- lib/src/action.rs
- lib/src/command/supervisor.rs
Had a similar issue as https://github.com/watchexec/watchexec/issues/240 and saw a typo in the error message
> Fix spawing -> spawning typo

- lib/src/filter/globset.rs
- lib/tests/filter_globset.rs
> globset: Always pass non-path events

- .github/workflows/clippy.yml
- .github/workflows/release-cli.yml
- .github/workflows/tests.yml
See https://github.com/actions/cache/issues/752
> Use gnu tar on windows CI

- README.md
The previous badge was broken. :)
> Readme: fix CI badge URL

- crates/cli/README.md
Add complex example how to wrap watchexec around plain converter tools to work around #456 for now
> Add complex converter tool wrapper example to docs

- Cargo.lock
- crates/lib/Cargo.toml
- crates/lib/src/command/supervisor.rs
- crates/lib/src/lib.rs
- crates/lib/src/signal/process.rs
See https://github.com/watchexec/cargo-watch/issues/238
> Reset process sigmask for Rust 1.66

- crates/cli/src/main.rs
> Exit explicitly when we're PID 1

- crates/lib/src/action/worker.rs
Reverts watchexec/watchexec#509
> Revert "Fix #375: urgent events bypass throttle"

- .github/workflows/release-cli.yml
> Switch away from set-output

- crates/cli/src/filterer/globset.rs
> Normalise paths to unix on windows for filtering only

- crates/bosion/examples/default/Cargo.lock
- crates/bosion/examples/no-git/Cargo.lock
- crates/bosion/examples/no-std/Cargo.lock
Regenerates the Cargo.lock files so that bosion tests pass in CI
> fix bosion tests

- crates/cli/src/lib.rs
> Fix logfile not creating if it doesn’t exist

- crates/bosion/README.md
> Fix bosion readme

- crates/cli/Cargo.toml
> Move fish completion in rpm and deb packaging to vendor-completions.d

- .clippy-lints
- crates/cli/src/args.rs
- doc/watchexec.1
- doc/watchexec.1.md
> feat(cli): Add NO_COLOR support

- crates/cli/src/args.rs
- doc/watchexec.1
- doc/watchexec.1.md
> doc: fix --on-busy-update help text

- Cargo.lock
- crates/bosion/Cargo.toml
- crates/bosion/examples/clap/Cargo.lock
- crates/bosion/examples/clap/src/main.rs
- crates/bosion/src/info.rs
- crates/bosion/src/lib.rs
It brings feature parity with similar crates.
> feat: Add git-describe support
