watchexec/watchexec

- Cargo.lock
- src/runner.rs
Instead of using conditionals and the `cfg` macro, allow for [`target_family` attributes](https://doc.rust-lang.org/reference.html#conditional-compilation).
> Use cfg attributes

- README.md
I had to figure out how to install watchexec with nightly using rustup.
A lot of people are probably not familiar with it, so include the commands.
> README: Add rustup command for installing with nightly

- Cargo.lock
- Cargo.toml
- src/lib.rs
- src/run.rs
Splitting up main.rs to a new run.rs so the main loop can be called as a
function, and publishing the `cli` module so `Args` can be built
programmatically from outside its `get_args` function, then adding a new lib.rs
entrypoint.
The resulting library interface is fairly simplistic, but should allow
watchexec to be embedded into other Rust programs without adding much to the
surface to be maintained.
The update to clap 2.22 is an artifact of this PR being developed specifically
for passcod/cargo-watch#65 as cargo-watch uses clap 2.22 features in its args.
While saying that, I do believe adding a library interface to watchexec would
be beneficial on its own.
> Add a library interface

- Cargo.toml
Hi, maintainers.
This pull request will disable bin's document. The reason why is that I caught the following error with `cargo doc`, `cargo doc --lib` and `cargo doc --bin watchexec`.
> error: cannot document a package where a library and a binary have the same name. Consider renaming one or marking the target as `doc = false`
> Resolving conflicted cargo documents

- Cargo.lock
- Cargo.toml
- src/lib.rs
- src/main.rs
- src/process.rs
- src/signal.rs
A few things to note here:
- The `libc` dependency was removed since it is "safer" to use the `libc` re-exported by `nix`.
This helps in situations where either `nix` or `watchexec` updates the `libc` and the APIs are incompatible.
- `from_nix_error` had to be implemented because `nix 0.9` [removed it](https://github.com/nix-rust/nix/pull/614/files#diff-b4aea3e418ccdb71239b96952d9cddb6L157). More [here](https://github.com/oconnor663/os_pipe.rs/pull/10).
The implementation borrows from `nix`.
> Update dependencies and other small improvements

- src/cli.rs
- src/run.rs
Addresses  #51
- Move `-d, --debug` flags to `-v, --verbose`
- Add configurable debounce timeout option behind `-d, --debounce`
> Add `-d, --debounce` option

- src/process.rs
This PR fixes lint warnings generated by cargo-clippy:
- **warning**: you should put `code` between ticks in the documentation
- **warning**: use of `or_insert` followed by a function call
- **warning**: it is more idiomatic to loop over containers instead of using explicit iteration methods
I have run `cargo test` and these changes do not break any of the tests :-)
reference:
--
* https://rust-lang-nursery.github.io/rust-clippy/v0.0.165/index.html#doc_markdown
* https://rust-lang-nursery.github.io/rust-clippy/v0.0.165/index.html#or_fun_call
* https://rust-lang-nursery.github.io/rust-clippy/v0.0.165/index.html#explicit_into_iter_loop
* https://github.com/rust-lang-nursery/rust-clippy
> fix (src/process.rs): fix cargo clippy linter warnings

- src/run.rs
This addresses warnings reported by cargo clippy on `src/run.rs`:
* warning: this expression borrows a reference that is immediately dereferenced by the compiler
reference:
- https://rust-lang-nursery.github.io/rust-clippy/v0.0.165/index.html#needless_borrow
- https://github.com/rust-lang-nursery/rust-clippy
> fix (src/run.rs): fixed cargo clippy warnings

- src/cli.rs
Use `tput reset` instead of `clear` so that scrollback is cleared in
addition to the currently visible portion of the terminal.
(Should this fallback to clear if `tput reset` fails? `tput reset` is mandated by [POSIX](http://pubs.opengroup.org/onlinepubs/009695399/utilities/tput.html) and seems to be available on basically everything even remotely unixy (except Android), so it probably isn't worth it.)
> Use `tput reset` to clear screen.

- src/run.rs
Works only on linux (not sure how error is named on other systems):
```
*** System notification limit is too small, falling back to polling mode.
*** For better performance increase system limit:
sysctl fs.inotify.max_user_watches=524288
*** Polling for changes every 1000 ms
```
Fixes #62
> Add a warning and fallback on polling mode if limit exceeded

- README.md
This makes the documentation reflect changes from commit 8bd9bb3.
This also converts indentation to spaces in the README (there was mixed indentation).
Closes https://github.com/mattgreen/watchexec/issues/86 and https://github.com/mattgreen/watchexec/issues/81.
> Update the environment variable documentation in README

- src/process.rs
**Use setsid() instead of setpgid()**
This makes it possible to run commands that allocates TTYs and still capture their output and reap the process on completion.
> setpgid — set process group ID for job control
> setsid — create session and set process group ID
With this in place, the `waitpid` call detects that the process has exited even if the process allocated a TTY, and is able to unblock the runner and continue.
Further, the output of the command is also shown in the controlling terminal.
---
This should fix #47. Test cases in #47 all work with this in place.
When command allocates a TTY, it's not just that no output is shown; the reaping locks forever. The calls to `waitpid` returns `StillRunning` and then never returns again. I don't know if the lack of output is the cause, a …
> Support running commands that allocate their own TTYs (*nix)

- src/cli.rs
- src/run.rs
In some situations cargo-watch passes non-canonicalized paths into `watch`, and these aren't matched against the regex correctly. Because of this, it calls a Handler's `on_update` method even when an ignored file is changed.
I ran into this when using `cargo watch` with a `build.rs` script that edited a file in a git ignored folder. This caused an infinite loop because the build would update an ignored file, which would cause the build again. 
Here's a minimal repro repo: https://github.com/SpiralP/rust-cargo-watch-test
This used to be part of `watch` but was moved out in aae5a216b0b7d381b7c8af2d032f0b959757efbf.
https://github.com/watchexec/watchexec/commit/aae5a216b0b7d381b7c8af2d032f0b959757efbf#diff-8643ebb587e63cc619cd28e00be6a7e5L58 to …
> Always canonicalize input paths

- Cargo.lock
- Cargo.toml
- src/lib.rs
It is not used and depends on very very old version of uuid.
Signed-off-by: Igor Gnatenko <i.gnatenko.brain@gmail.com>
> Drop mktemp dependency

- doc/watchexec.1
- doc/watchexec.1.html
- doc/watchexec.1.ronn
The options were out of date (e.g. `-d` was debug). This updates them to
match the help text.
This also adds some documentation about separating the command with --
so that clap doesn't eat the flags intended for the command.
> Update options in man page

- src/cli.rs
- src/ignore.rs
- src/lib.rs
- src/notification_filter.rs
- src/run.rs
ref. https://github.com/passcod/cargo-watch/issues/127
This adds support for a dedicated ignore file by the name of `.ignore` a
la `fd`, `ripgrep`, et. al.
This purely just mimics what `Gitignore` is doing except it doesn't
ignore `.git` directories. There might be more I need to tweak and the
interface might be too obtuse, but this is a first pass.
I've also added a `--no-ignore` flag which ignores both `.gitignore` and
the dedicated `.ignore`. It might make sense to add a specific flag that
ignores `.ignore` but respects `.gitignore` to support the old
behaviour, but I wasn't sure what to name it.
> Support a dedicated ignore file

- Makefile
- appveyor.yml
- ci/before_deploy.sh
This is to ensure that binaries built in this way are built reproducibly.
This way you'll also know if you messed up a release by not running `cargo update` before tagging.
> Use --locked to ensure reproducibility

- src/notification_filter.rs
Currently there is a mismatch between the semantics described in the README and what is implemented. This PR fixes this.
I assumed the behavior from the README is more desirable, so I implemented that.
> Call `make test` when any file changes in this directory/subdirectory, except for everything below `target`:
$ watchexec -i target make test
> fix the ignore path handling to match the README by ignoring everything below a directory

- src/cli.rs
- src/run.rs
Added the flag which allows to ignore incoming processes while some process is still in execution. Not sure if the implementation is correct regarding the 4 scenarios though. Would be great if someone could elaborate on that matter.
> #123 --watch-idle flag implementation

- src/cli.rs
The force-poll flag does not mention time units as opposed to the
debounce flag and to make it even more confusing, the comment in the
code says something else than the output:
*** Polling for changes every 2000 ms
This patch makes it clear what units are used.
> Mention time units explicitly in CLI interface

- Cargo.lock
- Cargo.toml
- src/gitignore.rs
- src/ignore.rs
See https://github.com/watchexec/watchexec/issues/146
This adds support for .gitignroe files in subdirectories of watched paths. 
It doesn't change the semantics of .ignore files.
> Include .gitignores in subdirectories

- src/cli.rs
.filename.kate-swp format according to https://unix.stackexchange.com/a/112400
> add Kate (KDE default editor) swap file to default ignores

- src/main.rs
- src/run.rs
Closes #159. This PR moves the call of `init_logger` out of the library portion of the code and into main.
Turned out to be very easy, and the usage of the `debug` flag is preserved.
I don't know what you want to do with the semver; this could be considered a breaking change in that any downstream clients that were using the lib and expecting to have logging initialised for them now need changing to do it themselves.
> Call init_logger from the binary code, not the library code

- README.md
We recently added `watchexec` to Webi. See  https://webinstall.dev/watchexec.
For reference:
[Webi](https://webinstall.dev) is different from other package managers in that it allows the user to install the _Official_ releases directly from the command line without first having to install a package manager or manually find the download link from the releases page.
So it's _much_ faster, much easier to remember, and has less system impact.
> add Webi install instructions

- src/cli.rs
- src/main.rs
- src/run.rs
Implements the feature requested in https://github.com/watchexec/watchexec/issues/138
> Add --changes-only option to only print path change information.

- src/gitignore.rs
This PR fixes the lookup for the root git directory. Now it correctly assigns the directory with `.git` to `top_level_git_dir`, rather than its descendant `path`.
This fixes issue where .gitignore files located above the watched path were ignored.
Also, unnecessary path clone was fixed.
> Fix lookup of the root git directory

- lib/src/process.rs
- lib/src/run.rs
With --on-update=do-nothing, we need to know when the process is done
before we can spawn a new one, but we never actually used to truly check
the process, only the presence or absence of a spawned process. That
process may have already completed, but because we don't wait on it when
in do-nothing mode, there is no opportunity to notice this.
So now we either actually check the completion status of the process (on
Windows), or we expose the `done` mutex value on demand (Unix).
Essentially this adds a way to check the completion status of the
process without blocking (modulo a mutex lock on unix).
Fixes #200
> Actually check process when querying for completion

- .github/workflows/release.yml
Hi! I recently set up an apt repo of cool rust CLI tools at https://apt.cli.rs. I added the i686/x86_64 musl debs to it, but I figured it would be useful to also generate aarch64 packages, so here is a PR which I believe should add that.
> Add arm64 musl build

- cli/README.md
Without pattern, `watchexec` 1.18.2 triggers on subdirectories.
> cli/README.md: Need glob pattern to ignore subdirs

- .github/workflows/merge.yml
- Cargo.lock
- crates/cli/Cargo.toml
- crates/cli/README.md
- crates/cli/src/filterer/common.rs
- crates/cli/src/lib.rs
- crates/filterer/globset/Cargo.toml
- crates/filterer/globset/README.md
- crates/filterer/ignore/Cargo.toml
- crates/filterer/ignore/README.md
- crates/filterer/tagged/Cargo.toml
- crates/filterer/tagged/README.md
- crates/lib/Cargo.toml
- crates/lib/README.md
- crates/lib/src/fs.rs
Fixes #382
Pushes the MSRV to 1.60, which will incur a minor version bump on a bunch of crates (not the CLI).
> Update Notify to stable

- completions/zsh
```sh
$ watchexec --shell=bash --█ # press tab here does not autocomplete watchexec command options
```
```sh
$ watchexec --shell=bash --█ # press tab here works as expected
```
> Fix zsh autocomplete after using --shell=bash

- .github/workflows/tests.yml
Current stable is 1.67, so bump the tested MSRV to 1.62
> Update effective MSRV

- doc/packages.md
Seems the APT package has changed name to `watchexec-cli`
> update package name

- Cargo.lock
- crates/ignore-files/Cargo.toml
- crates/ignore-files/src/discover.rs
All packages from the `gitoxide` have been renamed from `git-*` to `gix-*`. Additionally, this pull request updates from `git-config` v0.14.0 to `gix-config` v0.16.2
> Switch to gix-config because git-config is deprecated

- crates/lib/src/action/worker.rs
This will let signals through without waiting for the full debounce, for example.
> Fix #375: urgent events bypass throttle

- Cargo.lock
- crates/lib/Cargo.toml
- crates/lib/src/command/supervisor.rs
Enabled by command-group 2.1.0
Fixes #274.
> Kill process on drop when using command-group

- Cargo.lock
- crates/cli/src/config/runtime.rs
- crates/lib/src/action/outcome.rs
- crates/lib/src/action/outcome_worker.rs
This enables patterns like timeouts. A convenience `Outcome::wait_timeout()` is provided for the most common use.
Uses that pattern to fix `--restart`'s stop timeout (#544, another one I can't remember/find right now).
Also adds `Outcome::sequence` to build a sequence with `Both` from an iterator.
> Add Outcome::Race

- crates/ignore-files/src/filter.rs
This fixes the IgnoreFilter's `add_glob` function to make sure it applies to the proper GitIgnoreBuilder
> fix adding globs to the IgnoreFilter

- crates/ignore-files/Cargo.toml
- crates/ignore-files/src/error.rs
- crates/ignore-files/src/filter.rs
This fixes the issue where using `IgnoreFiler::new` with relative paths causes a runtime exception.
> handle relative paths when using Ignore programmatically

- crates/lib/src/command.rs
- crates/lib/src/command/tests.rs
CMD uses special handling for arguments to passed to `/C`. Unfortunately, this causes errors with quoted program names in these arguments.
This commit implements a workaround: When CMD is requested, we build a `std::process::Command` and pass the the argument to `/C` using the special `std::os::windows::process::CommandExt::raw_arg` method. The `StdCommand` is then converted to a `TokioCommand` and returned.
Once tokio-rs/tokio#5810 is fixed, this workaround can be removed.
Fixes #613
> Use raw_arg for CMD on Windows

- Cargo.lock
- crates/bosion/Cargo.toml
- crates/bosion/src/info.rs
Also disable default features of `gix` as they are not required.
> dep: bump gix from v0.44.1 => v0.47

- doc/packages.md
> Update Arch Linux package URL in packages.md

- crates/cli/src/config.rs
- crates/lib/src/action/worker.rs
Fixes #716 by also waiting for processes to quit
> Graceful quit on Ctrl-C

- crates/cli/integration/trailingargfile.sh
- crates/cli/src/args.rs
Fixes #717
argfile parses `@argfiles` at any point in the command, while we originally parsed only the first argument if it matched; therefore argfile was parsing `@`-arguments in the child command part, after `--`, which was undesired.
This keeps the argfile parsing anywhere improvement, plus the recursive argfile parsing, but stops at the first `--`.
> Fix argfile regression 

- bin/dates.mjs
- crates/cli/src/config.rs
- crates/supervisor/CHANGELOG.md
- crates/supervisor/src/job/state.rs
- crates/supervisor/src/job/task.rs
Two-parter:
- Supervisor's `Start` behaviour was wrong, _and_
- CLI would queue more than one starts on busy change
Fixes #726
> Fix queueing behaviour

- crates/cli/src/config.rs
- crates/cli/src/lib.rs
The thing I'm watching corrupts the screen something horrible when it shuts down.
Make `watchexec --clear reset` mean to completely destroy the contents of the screen during shutdown.
---
This obviously isn't where you would want this code, but:
* [in the middle of clean shutdown](https://github.com/watchexec/watchexec/blob/e4e8d3954601c778a5f4e2d442a99b4179361793/crates/lib/src/action/worker.rs#L83 ), we're inside lib watchexec (not cli), which doesn't know anything about the `clearscreen` library, so this doesn't feel like a good place; nor does it feel appropriate to call back to some config object / lambda here?
* the [quit worker code](https://github.com/watchexec/watchexec/blob/eb4f2ce201ab7074b00baebeb7d5dd0e748c6bcb/crates/cli/src/config.rs#L251) runs [after event …
> feat: under --clear reset, always reset at exit

- completions/bash
- completions/elvish
- completions/fish
- completions/nu
- completions/powershell
- completions/zsh
- crates/cli/README.md
- crates/cli/src/args.rs
- crates/cli/src/filterer/proglib/file.rs
- crates/cli/src/lib.rs
- crates/cli/src/state.rs
- doc/watchexec.1
- doc/watchexec.1.md
Fixes #814 
Also adds a `WATCHEXEC_TMPDIR` env variable that is used to override the location of tmpfiles, just for Watchexec.
> Don't create a tmpfile until one is needed

- crates/cli/src/args.rs
I ran into an issue where I provided a directory using the --watch flag but it gets treated non-recursively:
`watchexec -vvv --watch in -- ls -a`
Relevant log output (with path obscured):
`effective watched paths paths=[WatchedPath { path: "..in", recursive: false }]`
With the change from this PR:
`effective watched paths paths=[WatchedPath { path: "..in", recursive: true }]`
The behavior is now as expected. I'm assuming this was just a missed line when the non-recursive watch feature was added.
> fix(cli): recursive paths provided by user getting treated non-recursively

- Cargo.lock
- crates/cli/Cargo.toml
- crates/cli/src/args.rs
Closes #830 by going back to non-UNC paths on windows
sample.bat:
```
echo Hello world
```
`cargo run -r -- .\sample.bat` now runs as expected.
Added the same version of dunce as in `ignore-files/Cargo.toml`
> Replace std::fs::canonicalize with dunce::canonicalize

- crates/cli/src/args.rs
- crates/lib/tests/env_reporting.rs
- crates/project-origins/src/lib.rs
That should fix #886, from the [changes introduced in 2.1.0](https://github.com/watchexec/watchexec/compare/v2.0.0...v2.1.0).
> Make project origin absolute

- crates/filterer/ignore/tests/filtering.rs
- crates/ignore-files/src/filter.rs
Calls to `add_globs()` and `add_file()` dynamically create a new ignore entry if there isn't one at the location of `applies_in` param. This allows users to e.g. add globs to a path that previously has no ignore files in.
Fixes #907
> [ignore-files] Dynamically create ignore entries when calling `add_globs()` and `add_file()`

- Cargo.lock
- crates/lib/Cargo.toml
- crates/lib/src/error/runtime.rs
`ignore-files` in `watchexec` is only used for a deprecated error variant. `ignore-files` pulls in well over 20 extra transitive dependencies through gix which are just completely unused when using `watchexec` as a library by itself.
> Remove ignore-files dependency from watchexec

- Cargo.lock
- crates/bosion/src/lib.rs
- crates/cli/src/lib.rs
- crates/events/Cargo.toml
- crates/events/src/lib.rs
- crates/filterer/globset/src/lib.rs
- crates/filterer/ignore/Cargo.toml
- crates/filterer/ignore/src/lib.rs
- crates/ignore-files/src/filter.rs
- crates/ignore-files/src/lib.rs
- crates/lib/Cargo.toml
- crates/lib/src/lib.rs
- crates/project-origins/src/lib.rs
- crates/signals/src/lib.rs
- crates/supervisor/Cargo.toml
- crates/supervisor/src/lib.rs
Introduce `#![cfg_attr(not(test), warn(unused_crate_dependencies))]` to all crates to warn on unused (non-dev) dependencies. Plus a few warning fixes.
> Remove unused dependencies

- CONTRIBUTING.md
- crates/cli/src/args.rs
- crates/cli/src/args/logging.rs
- doc/watchexec.1
- doc/watchexec.1.md
I use `watchexec` on a lot of Rust projects, and I often set the `RUST_LOG` env var, either manually or automatically with tools like direnv.
This means that I end up seeing watchexec logs, even if I absolutely don't care about them.
Rust itself switched from `RUST_LOG` over to `RUSTC_LOG` quite a while ago, with a similar motivation.
---
Since `watchexec` will be used in Rust development environments, it makes sense to :
- Stop respecting the `RUST_LOG` env var
- use a custom `WATCHEXEC_LOG` for logging configuration instead
I don't know how you feel about it from a breaking change point of view. I feel like this is more breaking for developers that are used to `RUST_LOG` when debugging `watchexec`.
Thanks
> Use distinct `WATCHEXEC_LOG` logging filter env variable
